### ISSUE TITLE
Change y-axis from exponential to dollars

### ISSUE THREAD

**Issue by vmorales95** [pep93/sds192-mp2#1]
Want $ signs and money intervals.

**Comment by pep93** [comment]
Got it :)

**Comment by pep93** [comment]
Need to decided how we want to label/color code legends. Do we want to simplify them further to just have them color coded to show if the transaction type was in support of the candidate or opposing the candidate? Right now it's hard to distinguish between positive and negative support. Which is important since that's the whole point of our data graphic.
